#!/usr/bin/env python3
"""MEDS fast-loop numerics benchmark harness (MEDS_NUMERICS_SCOPING.md goal (b), section 5).

Sweeps the scheme x dt_fast x process-mask cross-product, runs each cell, and emits ONE tidy
CSV keyed by (scheme, dt_fast, mask, controller, rtol_all).  That table is the input to goal (c)
-- the config-driven integrator-selection rule -- so the point is the dataset, not the plot.

Configs are generated by PARSING the base TOML and re-serializing it, never by patching text.
That is deliberate: appending an override block to a config that already defines the same table
silently re-parents every key that follows it (a duplicate ``[soil]`` is not a merge), which is
a failure mode that looks exactly like "the setting had no effect".

Accuracy is measured against a REFERENCE cell -- by default the ARK integrator at the finest
dt_fast in the sweep, further refined by ``--ref-refine`` -- resampled onto the common daily
time axis.  A cell that fails to run is kept in the table with its error, rather than dropped,
so a sweep is never silently incomplete.

Usage
-----
  scripts/numerics_sweep.py --base cfg.toml --out runs/sweep1            # full default matrix
  scripts/numerics_sweep.py --base cfg.toml --out runs/sweep1 --dry-run  # list the cells only
  scripts/numerics_sweep.py --base cfg.toml --out runs/sweep1 \
      --schemes split ark --dt 1800 900 300 --masks full no_energy
"""

from __future__ import annotations

import argparse
import csv
import datetime as _dt
import itertools
import math
import os
import shutil
import subprocess
import sys
import time
from pathlib import Path

try:
    import tomllib  # py3.11+
except ModuleNotFoundError:  # py3.10 and older
    import tomli as tomllib

try:
    import netCDF4
except ModuleNotFoundError:
    netCDF4 = None


# --------------------------------------------------------------------------------------------
# Sweep axes (section 5.2).  Masks are NAMED presets rather than the raw 2^7, because most of the
# cross-product is not physically interesting -- these are the reductions worth attributing.
# --------------------------------------------------------------------------------------------
SCHEMES = {
    # name    -> {config path: value}
    "split":  {"fast.time_integrator": "split", "fast.integration_scheme": "split"},
    "picard": {"fast.time_integrator": "split", "fast.integration_scheme": "picard"},
    "ark":    {"fast.time_integrator": "ark",   "fast.integration_scheme": "split"},
    # ark_fixed: the embedded-error adaptive march is OFF and there is exactly ONE ESDIRK step per
    # dt_fast, so dt_fast IS the tableau step.  Needed for any convergence-ORDER study: with the
    # adaptive march on, refining dt_fast refines the OUTER coupling cadence (frozen pre-pass,
    # state-commit, mask restore) while the inner march keeps hitting the same fixed tolerance --
    # the measured slope is then the splitting order, not the tableau's.
    "ark_fixed": {"fast.time_integrator": "ark", "fast.integration_scheme": "split",
                  "fast.ark_adaptive": False, "fast.ark_fixed_substep": 1},
}

MASKS = {
    "full":       {},
    "no_energy":  {"veg_energy": False, "cas_energy": False, "soil_heat": False},
    "no_water":   {"soil_water": False},
    "no_hydro":   {"hydraulics": False},
    "no_co2":     {"cas_co2": False},
    # in_tableau: freeze EXACTLY the two components that are operator-split OUT of the ESDIRK
    # tableau (soil water + plant hydraulics).  What remains is entirely inside the tableau, so the
    # ARK's observed order on this mask is its order free of the splitting barrier (section 3.5/8d).
    "in_tableau": {"soil_water": False, "hydraulics": False},
    "hydro_only": {"veg_energy": False, "cas_energy": False, "cas_vapour": False,
                   "cas_co2": False, "soil_heat": False, "soil_water": False},
}

DT_DEFAULT = [1800, 900, 600, 300]

# Variables pulled from the daily stream.  (name, kind) -- "state" is compared as an RMSE,
# "flux" as a relative bias on the period total, which is how each is actually judged.
METRIC_VARS = [
    ("cas_temp_site",      "state"),
    ("soil_temp_top_site", "state"),
    ("et_site",            "flux"),
    ("gpp_site",           "flux"),
]

# Integrator WORK counters (section 5.3), emitted by the [output].numerics group.  These are the COST
# axis: exact, reproducible, and machine-independent, unlike wall-clock.  Reported as period totals.
WORK_VARS = [
    "work_integ_steps_site",
    "work_integ_rej_site",
    "work_soil_nsub_site",
    "work_hydro_nsub_site",
    "work_nonconv_site",
]


# --------------------------------------------------------------------------------------------
# Minimal TOML writer.  The base config round-trips through tomllib, so only the value types
# tomllib produces need to be emitted.  Comments are lost -- generated configs are artifacts.
# --------------------------------------------------------------------------------------------
def _fmt(v):
    if isinstance(v, bool):
        return "true" if v else "false"
    if isinstance(v, str):
        return '"' + v.replace("\\", "\\\\").replace('"', '\\"') + '"'
    if isinstance(v, (int,)):
        return str(v)
    if isinstance(v, float):
        return repr(v)
    if isinstance(v, (list, tuple)):
        return "[" + ", ".join(_fmt(x) for x in v) + "]"
    if isinstance(v, (_dt.datetime, _dt.date, _dt.time)):
        return v.isoformat()
    raise TypeError(f"cannot serialize {type(v).__name__} to TOML")


def dumps(d: dict) -> str:
    """Serialize nested dicts to TOML, scalars first so they land in the right table."""
    def walk(table: dict, prefix: str, out: list):
        scalars = {k: v for k, v in table.items() if not isinstance(v, dict)}
        tables = {k: v for k, v in table.items() if isinstance(v, dict)}
        if prefix and (scalars or not tables):
            out.append(f"[{prefix}]")
        for k, v in scalars.items():
            out.append(f"{k} = {_fmt(v)}")
        if scalars:
            out.append("")
        for k, v in tables.items():
            walk(v, f"{prefix}.{k}" if prefix else k, out)
    lines: list[str] = []
    walk(d, "", lines)
    return "\n".join(lines) + "\n"


def _parse_duration(v) -> int:
    """Seconds from a MEDS duration string ("900s", "5m", "1h", "1d") or a bare number."""
    if isinstance(v, (int, float)):
        return int(v)
    t = str(v).strip().lower()
    mult = {"s": 1, "m": 60, "h": 3600, "d": 86400}
    if t and t[-1] in mult:
        return int(float(t[:-1]) * mult[t[-1]])
    return int(float(t))


def deep_set(d: dict, path: str, value):
    node = d
    parts = path.split(".")
    for p in parts[:-1]:
        node = node.setdefault(p, {})
    node[parts[-1]] = value


# --------------------------------------------------------------------------------------------
# Cell construction
# --------------------------------------------------------------------------------------------
class Cell:
    def __init__(self, name, scheme, dt, mask, controller, rtol_all, is_ref=False):
        self.name = name
        self.scheme = scheme
        self.dt = dt
        self.mask = mask
        self.controller = controller
        self.rtol_all = rtol_all
        self.is_ref = is_ref
        self.wall = float("nan")
        self.exit = None
        self.error = ""

    def __repr__(self):
        return f"<{self.name}>"


def build_config(base: dict, cell: Cell, out_dir: Path) -> dict:
    cfg = _deepcopy(base)
    for path, value in SCHEMES[cell.scheme].items():
        deep_set(cfg, path, value)
    deep_set(cfg, "fast.dt_fast", f"{cell.dt}s")
    deep_set(cfg, "fast.step_controller", cell.controller)
    if cell.rtol_all > 0:
        deep_set(cfg, "fast.rtol_all", cell.rtol_all)
    for k, v in MASKS[cell.mask].items():
        deep_set(cfg, f"fast.mask.{k}", v)
    # Each cell writes into its own directory; the aggregated daily stream is what we read back.
    cell_dir = out_dir / cell.name
    deep_set(cfg, "output.enabled", True)
    deep_set(cfg, "output.dir", str(cell_dir))
    deep_set(cfg, "output.prefix", "s")
    deep_set(cfg, "output.daily.enabled", True)
    deep_set(cfg, "output.monthly.enabled", False)
    deep_set(cfg, "output.annual.enabled", False)
    deep_set(cfg, "output.water_fluxes", True)
    deep_set(cfg, "output.energy_fluxes", True)
    deep_set(cfg, "output.numerics", True)          # section 5.3 work counters = the cost axis
    if "io" in cfg:
        deep_set(cfg, "io.output_dir", str(cell_dir))
    return cfg


def _deepcopy(o):
    if isinstance(o, dict):
        return {k: _deepcopy(v) for k, v in o.items()}
    if isinstance(o, list):
        return [_deepcopy(v) for v in o]
    return o


# --------------------------------------------------------------------------------------------
# Metrics (section 5.3)
# --------------------------------------------------------------------------------------------
def read_series(cell_dir: Path) -> dict:
    """Concatenate the daily-tier files in time order -> {var: [values]}."""
    if netCDF4 is None:
        return {}
    files = sorted(cell_dir.glob("s-D-*.nc"))
    if not files:
        return {}
    out: dict[str, list] = {}
    for f in files:
        try:
            ds = netCDF4.Dataset(f)
        except OSError:
            continue
        with ds:
            for name in [v for v, _ in METRIC_VARS] + WORK_VARS:
                if name in ds.variables:
                    out.setdefault(name, []).extend([float(x) for x in ds.variables[name][:]])
    return out


def compare(series: dict, ref: dict) -> dict:
    """RMSE for states, relative bias on the period total for fluxes."""
    m = {}
    for name, kind in METRIC_VARS:
        a, b = series.get(name), ref.get(name)
        if not a or not b:
            continue
        n = min(len(a), len(b))
        a, b = a[:n], b[:n]
        if kind == "state":
            m[f"rmse_{name}"] = math.sqrt(sum((x - y) ** 2 for x, y in zip(a, b)) / n)
        else:
            sa, sb = sum(a), sum(b)
            m[f"bias_{name}"] = (sa - sb) / sb if abs(sb) > 0 else float("nan")
            m[f"total_{name}"] = sa
    return m


# --------------------------------------------------------------------------------------------
# Driver
# --------------------------------------------------------------------------------------------
def run_cell(exe: Path, cfg_path: Path, log_path: Path, timeout: int,
             repeats: int = 1) -> tuple[float, int, str]:
    """Run a cell `repeats` times and return the MINIMUM wall time.

    A single-shot whole-process clock is not a usable cost axis at these runtimes: it is quantised
    (~50 ms on this machine) and inflated by a fixed startup/IO cost comparable to the fast loop
    itself, which is enough to invert a scheme ranking.  Minimum-of-N is the standard estimator for
    a noisy floor-bounded measurement -- the fastest observed run is the one least perturbed by
    scheduler noise.  The caller subtracts a measured fixed overhead separately.
    """
    best, rc, err = float("inf"), 0, ""
    for i in range(max(1, repeats)):
        t0 = time.perf_counter()
        try:
            with open(log_path, "wb") as log:
                p = subprocess.run([str(exe), str(cfg_path)], stdout=log, stderr=subprocess.STDOUT,
                                   timeout=timeout)
            rc = p.returncode
        except subprocess.TimeoutExpired:
            return time.perf_counter() - t0, -1, f"timeout after {timeout}s"
        best = min(best, time.perf_counter() - t0)
        if rc != 0:
            tail = log_path.read_text(errors="replace").strip().splitlines()[-1:] or [""]
            return best, rc, tail[0][:200]
    return best, rc, err


def main(argv=None):
    ap = argparse.ArgumentParser(description=__doc__,
                                 formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--base", required=True, type=Path, help="base MEDS main config (TOML)")
    ap.add_argument("--out", required=True, type=Path, help="sweep output directory")
    ap.add_argument("--exe", type=Path, default=Path("build-debug/meds_main"))
    ap.add_argument("--schemes", nargs="+", default=list(SCHEMES), choices=list(SCHEMES))
    ap.add_argument("--dt", nargs="+", type=int, default=DT_DEFAULT)
    ap.add_argument("--masks", nargs="+", default=["full"], choices=list(MASKS))
    ap.add_argument("--controllers", nargs="+", default=["i"], choices=["i", "pi"])
    ap.add_argument("--rtol-all", nargs="+", type=float, default=[0.0],
                    help="0 = leave each sub-solver at its own tolerance")
    ap.add_argument("--ref-scheme", default="ark", choices=list(SCHEMES))
    ap.add_argument("--ref-refine", type=int, default=12,
                    help="reference dt = min(--dt)/this. Default 12, not 4: MEASURED on the forced ERA5 "
                         "census stand, a split@54 s reference carries 0.0168 K of its OWN CAS-T error "
                         "and 0.0065 K on soil-T -- ~30%% of the 0.05-0.06 K signals being ranked -- "
                         "while split@18 s carries 0.0042 / 0.0013 K for ~3 s more compute. Refining the "
                         "reference is the cheap way to remove reference bias; it does NOT remove MODEL "
                         "asymmetry between schemes (see [fast].cas_condensation).")
    ap.add_argument("--timeout", type=int, default=3600)
    ap.add_argument("--repeats", type=int, default=1,
                    help="run each cell N times and keep the MINIMUM wall time (>=5 for cost claims)")
    ap.add_argument("--overhead-cell", action="store_true", default=True,
                    help="also run a fast-loop-free OVERHEAD cell and report wall_sec_net")
    ap.add_argument("--dry-run", action="store_true")
    ap.add_argument("--keep-going", action="store_true", default=True)
    args = ap.parse_args(argv)

    if not args.base.is_file():
        ap.error(f"base config not found: {args.base}")
    with open(args.base, "rb") as fh:
        base = tomllib.load(fh)

    # dt_slow must be an integer multiple of dt_fast, so the refined reference dt has to DIVIDE the
    # slow step -- otherwise the reference cell dies in config validation and the whole sweep silently
    # loses its accuracy columns.  Snap down to the largest admissible divisor.
    dt_slow_s = _parse_duration(base.get("dt_slow", "1d"))
    ref_dt = max(1, min(args.dt) // args.ref_refine)
    while ref_dt > 1 and dt_slow_s % ref_dt != 0:
        ref_dt -= 1
    # ONE REFERENCE PER MASK.  A masked cell integrates a DIFFERENT physical system, so scoring it
    # against the full-physics reference measures the physics difference (degrees K), not the
    # integration error -- which is not what the accuracy columns are for.  Each cell is compared
    # to a finely-resolved run of its OWN mask, so the column means the same thing in every row.
    cells = []
    ref_of = {}
    for mask in args.masks:
        name = f"ref_{args.ref_scheme}_{ref_dt}_{mask}"
        ref_of[mask] = name
        cells.append(Cell(name, args.ref_scheme, ref_dt, mask, "i", 0.0, is_ref=True))
    for scheme, dt, mask, ctrl, rt in itertools.product(
            args.schemes, args.dt, args.masks, args.controllers, args.rtol_all):
        tag = f"{scheme}_{dt}_{mask}_{ctrl}" + (f"_r{rt:g}" if rt > 0 else "")
        cells.append(Cell(tag, scheme, dt, mask, ctrl, rt))

    print(f"sweep: {len(cells)} cells ({len(ref_of)} reference(s) @ dt={ref_dt}s, one per mask)")
    if args.dry_run:
        for c in cells:
            print(f"  {c.name}")
        return 0

    args.out.mkdir(parents=True, exist_ok=True)
    exe = args.exe.resolve()
    if not exe.is_file():
        ap.error(f"executable not found: {exe} (build first, or pass --exe)")

    for i, cell in enumerate(cells, 1):
        cell_dir = args.out / cell.name
        if cell_dir.exists():
            shutil.rmtree(cell_dir)
        cell_dir.mkdir(parents=True)
        cfg_path = args.out / f"{cell.name}.toml"
        cfg_path.write_text(dumps(build_config(base, cell, args.out)))
        cell.wall, cell.exit, cell.error = run_cell(
            exe, cfg_path, args.out / f"{cell.name}.log", args.timeout, repeats=args.repeats)
        status = "ok" if cell.exit == 0 else f"FAILED ({cell.error})"
        print(f"  [{i}/{len(cells)}] {cell.name:38s} {cell.wall:8.2f}s  {status}", flush=True)
        if cell.exit != 0 and not args.keep_going:
            break

    # Fixed-overhead probe: identical run with the fast loop OFF.  wall_sec minus this is the time
    # actually spent integrating, which is what a cost axis has to compare.  Without it, two cells
    # differing by 0.1 s of fast loop look ~equal because both carry ~0.15 s of startup and IO.
    overhead = float("nan")
    if args.overhead_cell:
        ov_cfg = _deepcopy(base)
        deep_set(ov_cfg, "fast.fast_biophysics_on", False)
        deep_set(ov_cfg, "output.enabled", False)
        ov_dir = args.out / "_overhead"
        if ov_dir.exists():
            shutil.rmtree(ov_dir)
        ov_dir.mkdir(parents=True)
        deep_set(ov_cfg, "io.output_dir", str(ov_dir))
        ov_path = args.out / "_overhead.toml"
        ov_path.write_text(dumps(ov_cfg))
        ow, orc, _oerr = run_cell(exe, ov_path, args.out / "_overhead.log", args.timeout,
                                  repeats=max(args.repeats, 3))
        if orc == 0:
            overhead = ow
            print(f"  fixed overhead (fast loop off, min-of-{max(args.repeats,3)}): {overhead:.3f}s")
        else:
            print("  WARNING: overhead cell failed; wall_sec_net will be empty", file=sys.stderr)

    by_name = {c.name: c for c in cells}
    ref_series = {}
    for mask, name in ref_of.items():
        s = read_series(args.out / name) if by_name[name].exit == 0 else {}
        if not s:
            print(f"WARNING: no reference series for mask '{mask}' -- its accuracy columns "
                  f"will be empty", file=sys.stderr)
        ref_series[mask] = s

    rows = []
    for cell in cells:
        row = {"cell": cell.name, "scheme": cell.scheme, "dt_fast_s": cell.dt, "mask": cell.mask,
               "controller": cell.controller, "rtol_all": cell.rtol_all,
               "is_reference": cell.is_ref, "reference": ref_of[cell.mask],
               "wall_sec": round(cell.wall, 3),
               "wall_sec_net": (round(cell.wall - overhead, 3) if overhead == overhead else ""),
               "repeats": args.repeats,
               "exit": cell.exit, "error": cell.error}
        if cell.exit == 0:
            series = read_series(args.out / cell.name)
            if ref_series.get(cell.mask):
                row.update(compare(series, ref_series[cell.mask]))
            for wv in WORK_VARS:                      # period totals -> one number per cell
                if series.get(wv):
                    row[wv] = sum(series[wv])
        rows.append(row)

    cols = list(dict.fromkeys(k for r in rows for k in r))
    csv_path = args.out / "sweep.csv"
    with open(csv_path, "w", newline="") as fh:
        w = csv.DictWriter(fh, fieldnames=cols)
        w.writeheader()
        w.writerows(rows)

    nfail = sum(1 for c in cells if c.exit != 0)
    print(f"\nwrote {csv_path}  ({len(rows)} rows, {nfail} failed)")
    # NOTE (honest gap): section 5.3 also asks for WORK counters -- f-evals, Newton iterations,
    # step rejections, accepted substeps.  Those live in column_budget_t and are not serialized
    # to netCDF yet, so they are absent here rather than estimated.  Wall-clock is the only cost
    # axis this version reports.
    return 0


if __name__ == "__main__":
    sys.exit(main())
