#!/usr/bin/env python3
"""MEDS fast-loop numerics benchmark harness (MEDS_NUMERICS_SCOPING.md goal (b), section 5).

Sweeps the scheme x dt_fast x process-mask cross-product, runs each cell, and emits ONE tidy
CSV keyed by (scheme, dt_fast, mask, controller, rtol_all).  That table is the input to goal (c)
-- the config-driven integrator-selection rule -- so the point is the dataset, not the plot.

Configs are generated by PARSING the base TOML and re-serializing it, never by patching text.
That is deliberate: appending an override block to a config that already defines the same table
silently re-parents every key that follows it (a duplicate ``[soil]`` is not a merge), which is
a failure mode that looks exactly like "the setting had no effect".

Accuracy is measured against a REFERENCE cell -- by default the ARK integrator at the finest
dt_fast in the sweep, further refined by ``--ref-refine`` -- resampled onto the common daily
time axis.  A cell that fails to run is kept in the table with its error, rather than dropped,
so a sweep is never silently incomplete.

Usage
-----
  scripts/numerics_sweep.py --base cfg.toml --out runs/sweep1            # full default matrix
  scripts/numerics_sweep.py --base cfg.toml --out runs/sweep1 --dry-run  # list the cells only
  scripts/numerics_sweep.py --base cfg.toml --out runs/sweep1 \
      --schemes split ark --dt 1800 900 300 --masks full no_energy
"""

from __future__ import annotations

import argparse
import csv
import datetime as _dt
import itertools
import math
import os
import shutil
import subprocess
import sys
import time
from pathlib import Path

try:
    import tomllib  # py3.11+
except ModuleNotFoundError:  # py3.10 and older
    import tomli as tomllib

try:
    import netCDF4
except ModuleNotFoundError:
    netCDF4 = None


# --------------------------------------------------------------------------------------------
# Sweep axes (section 5.2).  Masks are NAMED presets rather than the raw 2^7, because most of the
# cross-product is not physically interesting -- these are the reductions worth attributing.
# --------------------------------------------------------------------------------------------
SCHEMES = {
    # name    -> (time_integrator, integration_scheme)
    "split":  ("split", "split"),
    "picard": ("split", "picard"),
    "ark":    ("ark",   "split"),
}

MASKS = {
    "full":       {},
    "no_energy":  {"veg_energy": False, "cas_energy": False, "soil_heat": False},
    "no_water":   {"soil_water": False},
    "no_hydro":   {"hydraulics": False},
    "no_co2":     {"cas_co2": False},
    "hydro_only": {"veg_energy": False, "cas_energy": False, "cas_vapour": False,
                   "cas_co2": False, "soil_heat": False, "soil_water": False},
}

DT_DEFAULT = [1800, 900, 600, 300]

# Variables pulled from the daily stream.  (name, kind) -- "state" is compared as an RMSE,
# "flux" as a relative bias on the period total, which is how each is actually judged.
METRIC_VARS = [
    ("cas_temp_site",      "state"),
    ("soil_temp_top_site", "state"),
    ("et_site",            "flux"),
    ("gpp_site",           "flux"),
]


# --------------------------------------------------------------------------------------------
# Minimal TOML writer.  The base config round-trips through tomllib, so only the value types
# tomllib produces need to be emitted.  Comments are lost -- generated configs are artifacts.
# --------------------------------------------------------------------------------------------
def _fmt(v):
    if isinstance(v, bool):
        return "true" if v else "false"
    if isinstance(v, str):
        return '"' + v.replace("\\", "\\\\").replace('"', '\\"') + '"'
    if isinstance(v, (int,)):
        return str(v)
    if isinstance(v, float):
        return repr(v)
    if isinstance(v, (list, tuple)):
        return "[" + ", ".join(_fmt(x) for x in v) + "]"
    if isinstance(v, (_dt.datetime, _dt.date, _dt.time)):
        return v.isoformat()
    raise TypeError(f"cannot serialize {type(v).__name__} to TOML")


def dumps(d: dict) -> str:
    """Serialize nested dicts to TOML, scalars first so they land in the right table."""
    def walk(table: dict, prefix: str, out: list):
        scalars = {k: v for k, v in table.items() if not isinstance(v, dict)}
        tables = {k: v for k, v in table.items() if isinstance(v, dict)}
        if prefix and (scalars or not tables):
            out.append(f"[{prefix}]")
        for k, v in scalars.items():
            out.append(f"{k} = {_fmt(v)}")
        if scalars:
            out.append("")
        for k, v in tables.items():
            walk(v, f"{prefix}.{k}" if prefix else k, out)
    lines: list[str] = []
    walk(d, "", lines)
    return "\n".join(lines) + "\n"


def deep_set(d: dict, path: str, value):
    node = d
    parts = path.split(".")
    for p in parts[:-1]:
        node = node.setdefault(p, {})
    node[parts[-1]] = value


# --------------------------------------------------------------------------------------------
# Cell construction
# --------------------------------------------------------------------------------------------
class Cell:
    def __init__(self, name, scheme, dt, mask, controller, rtol_all, is_ref=False):
        self.name = name
        self.scheme = scheme
        self.dt = dt
        self.mask = mask
        self.controller = controller
        self.rtol_all = rtol_all
        self.is_ref = is_ref
        self.wall = float("nan")
        self.exit = None
        self.error = ""

    def __repr__(self):
        return f"<{self.name}>"


def build_config(base: dict, cell: Cell, out_dir: Path) -> dict:
    cfg = _deepcopy(base)
    integ, scheme = SCHEMES[cell.scheme]
    deep_set(cfg, "fast.time_integrator", integ)
    deep_set(cfg, "fast.integration_scheme", scheme)
    deep_set(cfg, "fast.dt_fast", f"{cell.dt}s")
    deep_set(cfg, "fast.step_controller", cell.controller)
    if cell.rtol_all > 0:
        deep_set(cfg, "fast.rtol_all", cell.rtol_all)
    for k, v in MASKS[cell.mask].items():
        deep_set(cfg, f"fast.mask.{k}", v)
    # Each cell writes into its own directory; the aggregated daily stream is what we read back.
    cell_dir = out_dir / cell.name
    deep_set(cfg, "output.enabled", True)
    deep_set(cfg, "output.dir", str(cell_dir))
    deep_set(cfg, "output.prefix", "s")
    deep_set(cfg, "output.daily.enabled", True)
    deep_set(cfg, "output.monthly.enabled", False)
    deep_set(cfg, "output.annual.enabled", False)
    deep_set(cfg, "output.water_fluxes", True)
    deep_set(cfg, "output.energy_fluxes", True)
    if "io" in cfg:
        deep_set(cfg, "io.output_dir", str(cell_dir))
    return cfg


def _deepcopy(o):
    if isinstance(o, dict):
        return {k: _deepcopy(v) for k, v in o.items()}
    if isinstance(o, list):
        return [_deepcopy(v) for v in o]
    return o


# --------------------------------------------------------------------------------------------
# Metrics (section 5.3)
# --------------------------------------------------------------------------------------------
def read_series(cell_dir: Path) -> dict:
    """Concatenate the daily-tier files in time order -> {var: [values]}."""
    if netCDF4 is None:
        return {}
    files = sorted(cell_dir.glob("s-D-*.nc"))
    if not files:
        return {}
    out: dict[str, list] = {}
    for f in files:
        try:
            ds = netCDF4.Dataset(f)
        except OSError:
            continue
        with ds:
            for name, _kind in METRIC_VARS:
                if name in ds.variables:
                    out.setdefault(name, []).extend([float(x) for x in ds.variables[name][:]])
    return out


def compare(series: dict, ref: dict) -> dict:
    """RMSE for states, relative bias on the period total for fluxes."""
    m = {}
    for name, kind in METRIC_VARS:
        a, b = series.get(name), ref.get(name)
        if not a or not b:
            continue
        n = min(len(a), len(b))
        a, b = a[:n], b[:n]
        if kind == "state":
            m[f"rmse_{name}"] = math.sqrt(sum((x - y) ** 2 for x, y in zip(a, b)) / n)
        else:
            sa, sb = sum(a), sum(b)
            m[f"bias_{name}"] = (sa - sb) / sb if abs(sb) > 0 else float("nan")
            m[f"total_{name}"] = sa
    return m


# --------------------------------------------------------------------------------------------
# Driver
# --------------------------------------------------------------------------------------------
def run_cell(exe: Path, cfg_path: Path, log_path: Path, timeout: int) -> tuple[float, int, str]:
    t0 = time.perf_counter()
    try:
        with open(log_path, "wb") as log:
            p = subprocess.run([str(exe), str(cfg_path)], stdout=log, stderr=subprocess.STDOUT,
                               timeout=timeout)
        rc, err = p.returncode, ""
    except subprocess.TimeoutExpired:
        return time.perf_counter() - t0, -1, f"timeout after {timeout}s"
    wall = time.perf_counter() - t0
    if rc != 0:
        tail = log_path.read_text(errors="replace").strip().splitlines()[-1:] or [""]
        err = tail[0][:200]
    return wall, rc, err


def main(argv=None):
    ap = argparse.ArgumentParser(description=__doc__,
                                 formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--base", required=True, type=Path, help="base MEDS main config (TOML)")
    ap.add_argument("--out", required=True, type=Path, help="sweep output directory")
    ap.add_argument("--exe", type=Path, default=Path("build-debug/meds_main"))
    ap.add_argument("--schemes", nargs="+", default=list(SCHEMES), choices=list(SCHEMES))
    ap.add_argument("--dt", nargs="+", type=int, default=DT_DEFAULT)
    ap.add_argument("--masks", nargs="+", default=["full"], choices=list(MASKS))
    ap.add_argument("--controllers", nargs="+", default=["i"], choices=["i", "pi"])
    ap.add_argument("--rtol-all", nargs="+", type=float, default=[0.0],
                    help="0 = leave each sub-solver at its own tolerance")
    ap.add_argument("--ref-scheme", default="ark", choices=list(SCHEMES))
    ap.add_argument("--ref-refine", type=int, default=4,
                    help="reference dt = min(--dt)/this")
    ap.add_argument("--timeout", type=int, default=3600)
    ap.add_argument("--dry-run", action="store_true")
    ap.add_argument("--keep-going", action="store_true", default=True)
    args = ap.parse_args(argv)

    if not args.base.is_file():
        ap.error(f"base config not found: {args.base}")
    with open(args.base, "rb") as fh:
        base = tomllib.load(fh)

    ref_dt = max(1, min(args.dt) // args.ref_refine)
    # ONE REFERENCE PER MASK.  A masked cell integrates a DIFFERENT physical system, so scoring it
    # against the full-physics reference measures the physics difference (degrees K), not the
    # integration error -- which is not what the accuracy columns are for.  Each cell is compared
    # to a finely-resolved run of its OWN mask, so the column means the same thing in every row.
    cells = []
    ref_of = {}
    for mask in args.masks:
        name = f"ref_{args.ref_scheme}_{ref_dt}_{mask}"
        ref_of[mask] = name
        cells.append(Cell(name, args.ref_scheme, ref_dt, mask, "i", 0.0, is_ref=True))
    for scheme, dt, mask, ctrl, rt in itertools.product(
            args.schemes, args.dt, args.masks, args.controllers, args.rtol_all):
        tag = f"{scheme}_{dt}_{mask}_{ctrl}" + (f"_r{rt:g}" if rt > 0 else "")
        cells.append(Cell(tag, scheme, dt, mask, ctrl, rt))

    print(f"sweep: {len(cells)} cells ({len(ref_of)} reference(s) @ dt={ref_dt}s, one per mask)")
    if args.dry_run:
        for c in cells:
            print(f"  {c.name}")
        return 0

    args.out.mkdir(parents=True, exist_ok=True)
    exe = args.exe.resolve()
    if not exe.is_file():
        ap.error(f"executable not found: {exe} (build first, or pass --exe)")

    for i, cell in enumerate(cells, 1):
        cell_dir = args.out / cell.name
        if cell_dir.exists():
            shutil.rmtree(cell_dir)
        cell_dir.mkdir(parents=True)
        cfg_path = args.out / f"{cell.name}.toml"
        cfg_path.write_text(dumps(build_config(base, cell, args.out)))
        cell.wall, cell.exit, cell.error = run_cell(
            exe, cfg_path, args.out / f"{cell.name}.log", args.timeout)
        status = "ok" if cell.exit == 0 else f"FAILED ({cell.error})"
        print(f"  [{i}/{len(cells)}] {cell.name:38s} {cell.wall:8.2f}s  {status}", flush=True)
        if cell.exit != 0 and not args.keep_going:
            break

    by_name = {c.name: c for c in cells}
    ref_series = {}
    for mask, name in ref_of.items():
        s = read_series(args.out / name) if by_name[name].exit == 0 else {}
        if not s:
            print(f"WARNING: no reference series for mask '{mask}' -- its accuracy columns "
                  f"will be empty", file=sys.stderr)
        ref_series[mask] = s

    rows = []
    for cell in cells:
        row = {"cell": cell.name, "scheme": cell.scheme, "dt_fast_s": cell.dt, "mask": cell.mask,
               "controller": cell.controller, "rtol_all": cell.rtol_all,
               "is_reference": cell.is_ref, "reference": ref_of[cell.mask],
               "wall_sec": round(cell.wall, 3), "exit": cell.exit, "error": cell.error}
        if cell.exit == 0 and ref_series.get(cell.mask):
            row.update(compare(read_series(args.out / cell.name), ref_series[cell.mask]))
        rows.append(row)

    cols = list(dict.fromkeys(k for r in rows for k in r))
    csv_path = args.out / "sweep.csv"
    with open(csv_path, "w", newline="") as fh:
        w = csv.DictWriter(fh, fieldnames=cols)
        w.writeheader()
        w.writerows(rows)

    nfail = sum(1 for c in cells if c.exit != 0)
    print(f"\nwrote {csv_path}  ({len(rows)} rows, {nfail} failed)")
    # NOTE (honest gap): section 5.3 also asks for WORK counters -- f-evals, Newton iterations,
    # step rejections, accepted substeps.  Those live in column_budget_t and are not serialized
    # to netCDF yet, so they are absent here rather than estimated.  Wall-clock is the only cost
    # axis this version reports.
    return 0


if __name__ == "__main__":
    sys.exit(main())
